apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: link-pedidocompra-contapagar
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    # - api.doc-custom.oondemand.com.br
    # - ai.doc-custom.oondemand.com.br
    # - doc-custom.oondemand.com.br
