apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: link-vitta
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - api.vitta.oondemand.com.br
