apiVersion: v1
kind: Service
metadata:
  name: link-vitta-service
  namespace: link-vitta
spec:
  type: NodePort
  selector:
    app: link-vitta
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
