apiVersion: v1
kind: Service
metadata:
  name: link-pedidocompra-contapagar-service
  namespace: link-pedidocompra-contapagar
spec:
  type: NodePort
  selector:
    app: link-pedidocompra-contapagar
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
